export enum ErrorCodes {
  NOT_FOUND_COMMENT = 'NOT_FOUND_COMMENT',
  NOT_FOUND_POST = 'NOT_FOUND_POST',
  ALREADY_REGISTERED_EMAIL = 'ALREADY_REGISTERED_EMAIL',
  ALREADY_REGISTERED_PHONE = 'ALREADY_REGISTERED_PHONE',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  LOGIN_REQUIRED = 'LOGIN_REQUIRED',
  UNAUTHORIZED_REQUEST = 'UNAUTHORIZED_REQUEST',
  NOT_FOUND_USER = 'NOT_FOUND_USER',
  INVALID_PASSWORD = 'INVALID_PASSWORD'
}
